### ISSUE TITLE
Hello, may I ask if you are familiar with the simulation of Example 9.3 in Chapter 9 of this book? I encountered a problem while reproducing it.

### ISSUE THREAD

**Issue by studentzmx** [yanseim/Applied-Nonlinear-Control-learning#1]
Hello, may I ask if you are familiar with the simulation of Example 9.3 in Chapter 9 of this book? I encountered a problem while reproducing it.您好，请问您了解这本书第九章，例题9.3的仿真么，我在进行复现时遇到了问题。

**Comment by yanseim** [comment]
同学好，我当时读的时候没有复现，不过我很愿意去写一遍验证一下。


但我最近在赶会议ddl。等我9.16之后找时间回复您。希望到时候能帮到您。我微信yan13429181166


祝好。

---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 23:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [yanseim/Applied-Nonlinear-Control-learning] Hello, may I ask if youare familiar with the simulation of Example 9.3 in Chapter 9 of this book? Iencountered a problem while reproducing it. (Issue #1)




 
Hello, may I ask if you are familiar with the simulation of Example 9.3 in Chapter 9 of this book? I encountered a problem while reproducing it.您好，请问您了解这本书第九章，例题9.3的仿真么，我在进行复现时遇到了问题。

**Comment by studentzmx** [comment]
If you have time, I hope to receive your help. My email is zhangmingx666@163.com . Please forgive me for any inconvenience.

**Comment by studentzmx** [comment]
If you have time, I hope to receive your help. My email is zhangmingx666@163.com . Please forgive me for any inconvenience.
